/**ACTIVIDAD 
 * AGREGAR 15 ELEMENTOS DE OBJETO PERSONA AL ARRAY CON DIFERENTES DATOS
 * 1.- MOSTRAR EL PROMEDIO DE LAS EDADES
 * 2.- FILTRAR POR NOMBRE O APELLIDO UN VALOR INGRESADO 
 * POR EL USUARIO DONDE COINCIDA CON LA LETRA O PALABRA
 * 
 */